/*
 * Copyright (C) 2025-2026 Axelix Labs
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.axelixlabs.axelix.sbs.spring.core.master;

import java.util.Optional;

import org.springframework.boot.info.GitProperties;
import org.springframework.core.annotation.Order;

import com.axelixlabs.axelix.common.api.registration.GitInfo;
import com.axelixlabs.axelix.common.api.registration.GitInfo.CommitAuthor;

/**
 * {@link GitInformationProvider} based on git.properties file generated by git commit id plugin.
 * It plugins natively supported by Spring Boot Actuator, so, we can just re-use the existing
 * Spring abstractions.
 *
 * @author Mikhail Polivakha
 */
@Order
public class CommitIdPluginGitInformationProvider implements GitInformationProvider {

    private final GitProperties gitProperties;

    private static final String AUTHOR_EMAIL_KEY = "commit.user.email";
    private static final String AUTHOR_NAME_KEY = "commit.user.name";
    private static final String AUTHOR_SHORT_SHA = "commit.id.abbrev";
    private static final String COMMIT_TIME = "commit.time";

    public CommitIdPluginGitInformationProvider(GitProperties gitProperties) {
        this.gitProperties = gitProperties;
    }

    @Override
    public Optional<GitInfo> getGitCommitInfo() {
        return Optional.of(new GitInfo(
                gitProperties.get(AUTHOR_SHORT_SHA),
                gitProperties.getBranch(),
                gitProperties.get(COMMIT_TIME),
                new CommitAuthor(gitProperties.get(AUTHOR_NAME_KEY), gitProperties.get(AUTHOR_EMAIL_KEY))));
    }
}
