server:
  port: 8080

# TODO: we need to think about the design of properties in general
spring:
  application:
    name: axelix
  mvc:
    servlet:
      path: /api/${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: [ "health" ]
axelix:
  master:
    discovery:
      auto: true
      platform: kubernetes
      kubernetes:
        kube-apiserver-url: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}
        sa-token-path: /var/run/secrets/kubernetes.io/serviceaccount/token
        ca-cert-path: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        filters:
          namespaces: default
    auth:
      jwt:
        algorithm: HMAC512
        lifespan: 12h
        signing-key: 22573444698685aa77750b88ad6e99ef1f94a7a909bc7df63f7a80666208c201ab7a584e6e05e6c9d0aa94b723f843ff
      static-admin:
        credentials:
          password: admin
          username: admin
      type: static-admin
      cookie:
        name: auth_token
        secure: false
