package com.nucleonforge.axile.sbs.spring.master;

import java.util.Optional;

import org.springframework.boot.info.GitProperties;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;

import com.nucleonforge.axile.common.api.registration.GitInfo;
import com.nucleonforge.axile.common.api.registration.GitInfo.CommitAuthor;

/**
 * {@link GitInformationProvider} based on git.properties file generated by git commit id plugin.
 * It plugins natively supported by Spring Boot Actuator, so, we can just re-use the existing
 * Spring abstractions.
 *
 * @author Mikhail Polivakha
 */
@Order(Ordered.LOWEST_PRECEDENCE)
public class CommitIdPluginGitInformationProvider implements GitInformationProvider {

    private final GitProperties gitProperties;

    private static final String AUTHOR_EMAIL_KEY = "commit.user.email";
    private static final String AUTHOR_NAME_KEY = "commit.user.name";
    private static final String AUTHOR_SHORT_SHA = "commit.id.abbrev";
    private static final String COMMIT_TIME = "commit.time";

    public CommitIdPluginGitInformationProvider(GitProperties gitProperties) {
        this.gitProperties = gitProperties;
    }

    @Override
    public Optional<GitInfo> getGitCommitInfo() {
        return Optional.of(new GitInfo(
                gitProperties.get(AUTHOR_SHORT_SHA),
                gitProperties.getBranch(),
                gitProperties.get(COMMIT_TIME),
                new CommitAuthor(gitProperties.get(AUTHOR_NAME_KEY), gitProperties.get(AUTHOR_EMAIL_KEY))));
    }
}
