/*
 * Copyright 2025-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.nucleonforge.axile.sbs.spring.master;

import java.util.List;

import org.springframework.boot.actuate.health.HealthEndpoint;
import org.springframework.boot.actuate.health.Status;
import org.springframework.util.Assert;
import org.springframework.util.CollectionUtils;

import com.nucleonforge.axile.common.api.registration.GitInfo;
import com.nucleonforge.axile.common.api.registration.ServiceMetadata;
import com.nucleonforge.axile.common.api.registration.ShortBuildInfo;

/**
 * Default implementation of {@link ServiceMetadataAssembler}.
 *
 * @author Mikhail Polivakha
 */
public class DefaultServiceMetadataAssembler implements ServiceMetadataAssembler {

    private final HealthEndpoint healthEndpoint;
    private final GitInformationProvider gitInformationProvider;
    private final ShortBuildInfoProvider shortBuildInfoProvider;
    private final LibraryDiscoverer libraryDiscoverer;

    @SuppressWarnings("NullAway")
    public DefaultServiceMetadataAssembler(
            HealthEndpoint healthEndpoint,
            LibraryDiscoverer libraryDiscoverer,
            List<GitInformationProvider> gitInformationProviders,
            List<ShortBuildInfoProvider> shortBuildInfoProviders) {

        this.healthEndpoint = healthEndpoint;
        this.libraryDiscoverer = libraryDiscoverer;
        this.gitInformationProvider = CollectionUtils.firstElement(gitInformationProviders);
        this.shortBuildInfoProvider = CollectionUtils.firstElement(shortBuildInfoProviders);

        Assert.notNull(this.healthEndpoint, "The HealthEndpoint must not be null");
        Assert.notNull(this.gitInformationProvider, missingGitInfoProvider());
        Assert.notNull(this.shortBuildInfoProvider, missingShortBuildInfoProvider());
    }

    @Override
    public ServiceMetadata assemble() {
        var shortBuildInfo = shortBuildInfoProvider.getShortBuildInfo();
        var gitCommitInfo = gitInformationProvider.getGitCommitInfo();

        return new ServiceMetadata(
                // TODO: remove the hardcoded version later
                "1.0.0-SNAPSHOT",
                shortBuildInfo.map(ShortBuildInfo::serviceVersion).orElse(""),
                gitCommitInfo.map(GitInfo::commitShaShort).orElse(""),
                System.getProperty("java.version"),
                libraryDiscoverer
                        .getLibraryVersion("spring-boot", "org.springframework.boot")
                        .orElse(""),
                getCurrentHealth());
    }

    private ServiceMetadata.HealthStatus getCurrentHealth() {
        Status status = healthEndpoint.health().getStatus();

        if (status == Status.UP) {
            return ServiceMetadata.HealthStatus.UP;
        }

        if (status == Status.DOWN) {
            return ServiceMetadata.HealthStatus.DOWN;
        }

        // defaulting to unknown in case of UNKNOWN, OUT_OF_SERVICE and custom statuses
        return ServiceMetadata.HealthStatus.UNKNOWN;
    }

    private static String missingGitInfoProvider() {
        return """
            There is no GitInformationProvider available for this service.
            This means that the axile's build plugin is not in use, and also
            there is no git.properties file in classpath (generated by git-commit-id plugin)
            """;
    }

    private static String missingShortBuildInfoProvider() {
        return """
            There is no ShortBuildInfoProvider available for this service.
            This means that the axile's build plugin is not in use, and also
            there is no git.properties file in classpath (generated by git-commit-id plugin)
            """;
    }
}
