name: Build / Deploy Backend

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '!front-end/**'
      - '!docs/**'
      - '!infra/**'
      - '!.editorconfig'
      - '!.gitignore'
      - 'master/**'
      - 'sbs/**'
      - '.github/workflows/backend.yaml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'front-end/**'
      - '.github/workflows/frontend.yaml'

env:
  SHOULD_DEPLOY: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' }}

jobs:
  check-linked-issues:
    if: ${{ !(github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check for linked issues
        uses: nearform-actions/github-action-check-linked-issues@v1
        with:
          exclude-labels: "refactoring"

  build-deploy-source:
    runs-on: ubuntu-latest
    env:
      DOCKER_CR_OAUTH_TOKEN: ${{ secrets.DOCKER_CR_OAUTH_TOKEN }}
      CR_URL: ${{ vars.CR_URL }}
      CR_MASTER_REPOSITORY: ${{ vars.CR_MASTER_REPOSITORY }}
      KUBE_CONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64 }}

      # These are needed in order to publish the final build artifacts into Nexus package registry
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_HOST_PORT: ${{ secrets.NEXUS_HOST_PORT }}
      STORE_PASS: ${{ secrets.STORE_PASS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # Configuration Cache in encrypted with this key
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
          # See https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#using-the-cache-read-only
          cache-read-only: false

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      # TODO: We probably would want here to not use build-cache for releases of production artifacts
      - name: Gradle build
        run: ./gradlew build --configuration-cache --build-cache

      - name: Download and trust Nexus SSL certificate for Gradle
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        run: |
          TRUSTSTORE="$JAVA_HOME/lib/security/cacerts"
          openssl s_client -connect $NEXUS_HOST_PORT -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM > nexus.crt
          sudo keytool -importcert -file nexus.crt -alias nexus-ssl -keystore $TRUSTSTORE -storepass $STORE_PASS -noprompt
          
          echo "org.gradle.jvmargs=-Djavax.net.ssl.trustStore=$TRUSTSTORE -Djavax.net.ssl.trustStorePassword=$STORE_PASS" >> $HOME/.gradle/gradle.properties

      - name: Publish Libraries to Nexus
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        run: ./gradlew publish

      - name: Set up Docker
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        uses: docker/setup-docker-action@v4

      - name: Build Docker Image
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        # TODO:
        #  1. extract version from gradle.properties file later on. For now hardcoded is fine
        #  2. And also we need to take the repository part inside the image name from the terraform output
        run: |
          docker build --tag $CR_URL/$CR_MASTER_REPOSITORY/master:1.0.0-SNAPSHOT --file master/docker/Dockerfile .

      - name: Docker login to Yandex Cloud CR
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        # TODO: Is it possible to authenticate via service account? Cause currently here in the OAUTH_TOKEN is my token
        run: echo $DOCKER_CR_OAUTH_TOKEN | docker login --username oauth --password-stdin $CR_URL

      - name: Docker push to Yandex Cloud CR
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        run: docker push $CR_URL/$CR_MASTER_REPOSITORY/master:1.0.0-SNAPSHOT

      - name: Docker logout
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        run: docker logout

      - name: Checkout source code
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        uses: actions/checkout@v4

      - name: Setup Helm
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.14.0

      - name: Deploy master to K8S
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        working-directory: master/chart
        run: |
          mkdir -p ~/.kube
          touch ~/.kube/config
          echo "$KUBE_CONFIG_BASE64" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          helm upgrade --install master . -f values.yaml

  dispatch:
    needs: [build-deploy-source]
    strategy:
      matrix:
        playground_repo: [
          'Nucleon-Forge/notification-service',
          'Nucleon-Forge/feature-service',
          'Nucleon-Forge/spring-petclinic'
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
          repository: ${{ matrix.playground_repo }}
          event-type: monorepo-backend-updated