name: Build / Deploy Backend

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '!front-end/**'
      - '!docs/**'
      - '!infra/**'
      - '!.editorconfig'
      - '!.gitignore'
      - 'master/**'
      - 'sbs/**'
  pull_request:
    branches: [ master ]

jobs:
  build-source:
    runs-on: ubuntu-latest
    env:
      # These are needed in order to publish the final build artifacts into GitHub package registry
      USERNAME: ${{ github.actor }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # Configuration Cache in ecrypted with this key
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
          # See https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#using-the-cache-read-only
          cache-read-only: false

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      # TODO: We probably would want here to not use build-cache for releases of production artifacts
      - name: Gradle build
        run: ./gradlew build --configuration-cache --build-cache

      - name: Stage JAR file
        uses: actions/upload-artifact@v4
        with:
          name: master-jar
          path: master/build/libs/master.jar
          retention-days: 3

  build-image:
    env:
      DOCKER_CR_OAUTH_TOKEN: ${{ secrets.DOCKER_CR_OAUTH_TOKEN }}
      CR_URL: ${{ vars.CR_URL }}
      CR_MASTER_REPOSITORY: ${{ vars.CR_MASTER_REPOSITORY }}
    name: Build Docker container for the master and deploy image to Container Registry
    runs-on: ubuntu-latest
    needs: build-source
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Download staged jar
        uses: actions/download-artifact@v5
        with:
          name: master-jar

      - name: Build Docker Image
        # TODO:
        #  1. extract version from gradle.properties file later on. For now hardcoded is fine
        #  2. And also we need to take the repository part inside the image name from the terraform output
        run: |
          docker build --tag $CR_URL/$CR_MASTER_REPOSITORY/master:1.0.0-SNAPSHOT --file master/docker/Dockerfile .

      - name: Docker login to Yandex Cloud CR
        # TODO: Is it possible to authenticate via service account? Cause currently here in the OAUTH_TOKEN is my token
        run: echo $DOCKER_CR_OAUTH_TOKEN | docker login --username oauth --password-stdin $CR_URL

      - name: Docker push to Yandex Cloud CR
        run: docker push $CR_URL/$CR_MASTER_REPOSITORY/master:1.0.0-SNAPSHOT

      - name: Docker logout
        run: docker logout

  deploy-to-test:
    env:
      KUBE_CONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64 }}
    name: Deploy the Helm Chart to Cloud
    runs-on: ubuntu-latest
    needs: build-image
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.14.0

      - name: Deploy master to K8S
        working-directory: master/chart
        run: |
          mkdir -p ~/.kube
          touch ~/.kube/config
          echo "$KUBE_CONFIG_BASE64" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          helm upgrade --install master . -f values.yaml
