name: Build / Deploy Front-End

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'front-end/**'
      - 'distributions/**'
      - '.github/workflows/frontend.yaml'
  pull_request:
    branches: [ master ]
    paths:
      - 'front-end/**'
      - '.github/workflows/frontend.yaml'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-linked-issues:
    if: ${{ !(github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check for linked issues
        uses: nearform-actions/github-action-check-linked-issues@v1
        with:
          exclude-labels: "refactoring"
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-end
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint application
        run: npm run lint

      - name: CSS lint application
        run: npm run lint-css

      - name: Run tests
        run: npm test
  deploy:
    needs: lint-and-test
    env:
      DOCKER_CR_OAUTH_TOKEN: ${{ secrets.DOCKER_CR_OAUTH_TOKEN }}
      # TODO: Rename the CR variable. We're likely going to use multiple CRs
      CR_URL: ${{ vars.CR_URL }}
      IMAGE_REPOSITORY: ${{ vars.CR_URL }}/${{ vars.CR_MASTER_REPOSITORY }}
      IMAGE_NAME: master-fe
      KUBE_CONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64 }}
    name: Build nginx Docker container
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Read Gradle Properties file
        uses: madhead/read-java-properties@4
        id: gradleProperties
        with:
          file: gradle.properties
          property: axelixVersion

      - name: Build Docker Image
        # TODO:
        #  For now the version of package is hardcoded both in package.json and in here. We later would need to
        #  find a way to manage it correctly.
        run: |
          docker build --tag $IMAGE_REPOSITORY/$IMAGE_NAME:${{ steps.gradleProperties.outputs.value }} --file front-end/Dockerfile .

      - name: Docker login to Yandex Cloud CR
        # TODO: Is it possible to authenticate via service account? Cause currently here in the OAUTH_TOKEN is a maintainer's PAT
        run: echo $DOCKER_CR_OAUTH_TOKEN | docker login --username oauth --password-stdin $CR_URL

      - name: Docker push to Yandex Cloud CR
        run: docker push $IMAGE_REPOSITORY/$IMAGE_NAME:${{ steps.gradleProperties.outputs.value }}

      - name: Docker logout
        run: docker logout

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.14.0

      - name: Deploy master to K8S
        working-directory: distributions/chart
        run: |
          mkdir -p ~/.kube
          touch ~/.kube/config
          echo "$KUBE_CONFIG_BASE64" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          helm upgrade \
            --set frontend.image.pullPolicy=Always \
            --set backend.image.pullPolicy=Always \
            --set frontend.image.name=$IMAGE_REPOSITORY/$IMAGE_NAME \
            --set frontend.image.tag=${{ steps.gradleProperties.outputs.value }} \
            --set backend.image.name=$IMAGE_REPOSITORY/master \
            --set backend.image.tag=${{ steps.gradleProperties.outputs.value }} \
            --install master . \
            -f values.yaml
